"""Add active field to users

Revision ID: 1711b935a099
Revises: 153bb41eb712
Create Date: 2015-04-12 19:41:08.338000

"""

# revision identifiers, used by Alembic.
revision = '1711b935a099'
down_revision = '153bb41eb712'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('active', sa.Boolean(), nullable=False, default=True, server_default="true"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'active')
    ### end Alembic commands ###
